version: "3"
services:
  app:
      container_name: covid-19-tracker
      build:
          context: .
          dockerfile: Dockerfile
      entrypoint: ['/etc/startup.sh']
      ports:
          - 5001:5000
      environment:
        - FLASK_ENV=development
        - FLASK_DEBUG=true
        - REDIS_URL=redis://redis_store:6379
      volumes:
        - ${PWD}:/usr/src/www
        - ${PWD}/logs:/tmp/logs
      depends_on:
        - redis_store
#      networks:
#        - host
  redis_store:
    image: redis:latest

#networks:
#  host:
